# Generated by Django 4.2.3 on 2023-07-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="parameter", old_name="name", new_name="user",
        ),
        migrations.AddField(
            model_name="parameter",
            name="option",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="parameter", name="value", field=models.CharField(max_length=50),
        ),
    ]
