# Generated by Django 4.2.3 on 2023-07-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0002_rename_name_parameter_user_parameter_option_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameter",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
