# Generated by Django 4.2.3 on 2023-07-23 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0003_parameter_version"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParameterHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=30)),
                ("option", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=50)),
                ("created_day", models.DateTimeField()),
                ("is_active", models.BooleanField()),
                (
                    "parameter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Config.parameter",
                    ),
                ),
            ],
        ),
    ]
