# Generated by Django 4.2.3 on 2023-07-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Config", "0004_parameterhistory"),
    ]

    operations = [
        migrations.RemoveField(model_name="parameter", name="is_active",),
        migrations.RemoveField(model_name="parameterhistory", name="is_active",),
        migrations.AddField(
            model_name="parameter",
            name="deleted_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parameterhistory",
            name="deleted_day",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="parameterhistory",
            name="modified_day",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
